version: '3.2'
services:
  prometheus:
    image: 'cirocosta/prom'
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.config.yml'
    ports:
      - '9090:9090'
    network_mode: 'host'
