version: '3.2'
services:
  not-found:
    image: 'cirocosta/prom'

  working:
    image: 'cirocosta/prom'
    volumes:
      - './prometheus.working.yml:/etc/prometheus/prometheus.env.yml'

  unset:
    image: 'cirocosta/prom'
    volumes:
      - './prometheus.unset.yml:/etc/prometheus/prometheus.env.yml'
        
